export const table_words = [
  {
    id: "10847",
    english: "butterfly",
    transcription: "[ ˈbʌtəflaɪ ]",
    russian: "бабочка",
  },
  {
    id: "10848",
    english: "hedgehog",
    transcription: "hedgehog",
    russian: "ёжик",
  },
  {
    id: "10853",
    english: "apple",
    transcription: "[apple]",
    russian: "яблоко",
  },
  {
    id: "10854",
    english: "pear",
    transcription: "[peə]",
    russian: "груша",
  },
  {
    id: "10858",
    english: "hedgehog",
    transcription: "[ ˈhedʒhɒɡ ]",
    russian: "еж",
  },
  {
    id: "10862",
    english: "carrot",
    transcription: "[ˈkærət]",
    russian: "морковка",
  },
  {
    id: "10865",
    english: "plum",
    transcription: "[plʌm]",
    russian: "слива",
  },
  {
    id: "10866",
    english: "apple",
    transcription: "[apple]",
    russian: "яблоко",
  },
  {
    id: "10867",
    english: "plum",
    transcription: "[plʌm]",
    russian: "слива",
  },
  {
    id: "10869",
    english: "carrot",
    transcription: "[ˈkærət]",
    russian: "морковка",
  },
  {
    id: "10870",
    english: "butterfly",
    transcription: "[ ˈbʌtəflaɪ ]",
    russian: "бабочка",
  },
  {
    id: "10871",
    english: "hedgehog",
    transcription: "[ ˈhedʒhɒɡ ]",
    russian: "еж",
  },
  {
    id: "10872",
    english: "unicorn",
    transcription: "[ˈyo͞onəˌkôrn]",
    russian: "единорог",
  },
  {
    id: "10873",
    english: "butterfly",
    transcription: "[ ˈbʌtəflaɪ ]\t",
    russian: "бабочка",
  },
];
