export const words = [
  {
    id: "10847",
    word: "butterfly",
    transcription: "[ ˈbʌtəflaɪ ]",
    russian: "бабочка",
  },
  // {
  //   id: "10848",
  //   word: "hedgehog",
  //   transcription: "hedgehog",
  //   russian: "ёжик",
  // },
  // {
  //   id: "10853",
  //   word: "apple",
  //   transcription: "[apple]",
  //   russian: "яблоко",
  // },
  // {
  //   id: "10854",
  //   word: "pear",
  //   transcription: "[peə]",
  //   russian: "груша",
  // },
  // {
  //   id: "10858",
  //   word: "hedgehog",
  //   transcription: "[ ˈhedʒhɒɡ ]",
  //   russian: "еж",
  // },
  // {
  //   id: "10862",
  //   word: "carrot",
  //   transcription: "[ˈkærət]",
  //   russian: "морковка",
  // },
  // {
  //   id: "10865",
  //   word: "plum",
  //   transcription: "[plʌm]",
  //   russian: "слива",
  // },
  // {
  //   id: "10866",
  //   word: "apple",
  //   transcription: "[apple]",
  //   russian: "яблоко",
  // },
  // {
  //   id: "10867",
  //   word: "plum",
  //   transcription: "[plʌm]",
  //   russian: "слива",
  // },
  // {
  //   id: "10869",
  //   word: "carrot",
  //   transcription: "[ˈkærət]",
  //   russian: "морковка",
  // },
  // {
  //   id: "10870",
  //   word: "butterfly",
  //   transcription: "[ ˈbʌtəflaɪ ]",
  //   russian: "бабочка",
  // },
  // {
  //   id: "10871",
  //   word: "hedgehog",
  //   transcription: "[ ˈhedʒhɒɡ ]",
  //   russian: "еж",
  // },
  // {
  //   id: "10872",
  //   word: "unicorn",
  //   transcription: "[ˈyo͞onəˌkôrn]",
  //   russian: "единорог",
  // },
  // {
  //   id: "10873",
  //   word: "butterfly",
  //   transcription: "[ ˈbʌtəflaɪ ]\t",
  //   russian: "бабочка",
  // },
];
